services:
  saynote:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - .:/app
      - saynote_node_modules:/app/node_modules

volumes:
  saynote_node_modules:
